config/routes.rb
Rails.application.routes.draw do
  root "todos#index"

  resources :todos

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :todos, only: [:index, :show]
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taged_todos
  has_many :todos, through: :taged_todos
end

app/models/taged_todo.rb
class TagedTodo < ActiveRecord::Base
  belongs_to :todo
  belongs_to :tag
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  has_many :taged_todos
  has_many :tags, through: :taged_todos
  validates :name, presence: true
end

app/controllers/api/v1/todos_controller.rb
class Api::V1::TodosController < ApplicationController

  def index
    render json: Todo.all
  end

  def show
    render json: Todo.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.all
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path
    else
      render :edit
    end
  end

  def destroy
    if @todo.destroy
      redirect_to todos_path
    else
      render :index
    end
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todopractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit <%= @todo.name %></h1>

app/views/todos/index.html.erb
<h1>Todos</h1>

<% @todos.each do |todo| %>
  <p><%= link_to todo.name, todo_path(todo) %> | tags: <% todo.tags.each do |tag| %>
    <%= tag.title %>,
  <% end %>
  </p>
<% end %>

<%= link_to "New", new_todo_path %>

app/views/todos/new.html.erb
<h1>New</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<%= @todo.name %>